### ISSUE TITLE
after installing a pip and modules, still getting this

### ISSUE THREAD

**Issue by DIBMS** [pratikpv/cryptocurrency_data_downloader#1]
cryptocurrency_data_downloader-master\download_data_from_binance.py", line 4, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

**Comment by jitvimol** [comment]
You need install binance package via pip first (in terminal)

command : pip install python-binance

**Comment by DIBMS** [comment]
yea, I did it reinstalling the pip, and problem disappear, but I have no ideal for this, thanks for any help :)
Step 0:Downloading data from 2019-11-16 01:00:00 to 2019-11-17 01:00:00
Traceback (most recent call last):
  File "c:\Users\vikto\Downloads\cryptocurrency_data_downloader-master\cryptocurrency_data_downloader-master\download_data_from_binance.py", line 178, in <module>
    download_data_from_binance(symbol, from_date, to_date, output_filename, step=1, pause=-1, simulate=False)
  File "c:\Users\vikto\Downloads\cryptocurrency_data_downloader-master\cryptocurrency_data_downloader-master\download_data_from_binance.py", line 86, in download_data_from_binance
    klines = binance_client.get_historical_klines(symbol, Client.KLINE_INTERVAL_1HOUR,
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 794, in get_historical_klines    first_valid_ts = self._get_earliest_valid_timestamp(symbol, interval)
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 747, in _get_earliest_valid_timestamp
    kline = self.get_klines(
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 734, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\vikto\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 230, in _handle_response     
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

**Comment by vishalkhialani** [comment]
symbol_list = ['LTCUSDT', 'ETHUSDT', 'BTCUSDT'] to fix the invalid symbol
